[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "recurrent-mgd"
version = "0.1"
description="A simplified repository for training recurrent neural networks (RNNs) with multiplexed gradient descent (MGD)."
dynamic = ["dependencies"] 